#ifndef __MSGS_H__
#define __MSGS_H__

#define MAX_PAYLOAD_SIZE  128

struct MSG_BODY
{
  uint8_t cmd;
  uint8_t len;
  uint8_t payload[MAX_PAYLOAD_SIZE];
};

#define MSG_BODY_SIZE   sizeof(MSG_BODY)

enum CMD_TYPE
{
  /*COMMANDS*/
  NO_CMD = 0,
  SET_NETWORK_NAME,
  SET_NETWORK_PASS,
  GET_NETWORK_NAME,
  GET_NETWORK_PASS,
  GET_DEVICE_NAME,
  CONNECT_TO_AP,
  DISCONNECT_FROM_AP,
  START_AP,
  STOP_AP,
  START_NETWORK_HELPER,
  STOP_NETWORK_HELPER,
  ADD_SUBSCRIPTION,
  REMOVE_SUBSCRIPTION,
  SAVE,
  GET_CONNECTION_STATE,
  REBOOT,
  SET_SERVER_ADDR,
  SET_SERVER_PORT,
  SET_USER_NAME,
  SET_USER_PASS,
  GET_SERVER_ADDR,
  GET_SERVER_PORT,
  GET_USER_NAME,
  GET_USER_PASS,
  CONNECT_TO_SERVER,
  DISCONNECT_FROM_SERVER,
  VERSION,
  TIME,
  SET_TIME_OFFSET,
  GET_IP,
  SET_PUB_ALIAS,
  SET_SUB_ALIAS,
  CLEAR_PUB_LIST,
  CLEAR_SUB_LIST,
  PUB_INFO,
  INVALID_CMD,

  /*NOTIFY*/
  NO_NOTIFY = 0x80,
  NETWORK_STATE_CHANGE,
  NETWORK_CHANGE,
  MQTT_STATE_CHANGE,
  SUBSCRIPTION_CHANGE,
  INVALID_NOTIFY
};

enum NETWORK_STATE_CHANGE_TYPE
{
  NO_CHANGE = 0,
  DISCONNECTED,
  CONNECTING_TO_AP,
  CONNECTED_TO_AP,
  ACTING_AS_AP,
  UNKNOWN_STATE
};

#endif
