#ifndef __MSGS_H__
#define __MSGS_H__

#include <cstdint>

#define MAX_PAYLOAD_SIZE  128

struct MSG_BODY
{
  uint8_t cmd;
  uint8_t len;
  uint8_t payload[MAX_PAYLOAD_SIZE];
};

#define MSG_BODY_SIZE   sizeof(MSG_BODY)

enum CMD_TYPE
{
  /*COMMANDS*/
  NO_CMD = 0,
  SET_NETWORK_NAME,
  SET_NETWORK_PASS,
  GET_NETWORK_NAME,
  GET_NETWORK_PASS,
  GET_DEVICE_NAME,
  CONNECT_TO_AP,
  DISCONNECT_FROM_AP,
  START_AP,
  STOP_AP,
  START_NETWORK_HELPER,
  STOP_NETWORK_HELPER,
  ADD_SUBSCRIPTION,
  REMOVE_SUBSCRIPTION,
  SAVE,
  GET_CONNECTION_STATE,
  INVALID_CMD,

  /*NOTIFY*/
  NO_NOTIFY = 0x80,
  NETWORK_STATE_CHANGE,
  NETWORK_CHANGE,
  SUBSCRIPTION_CHANGE,
  INVALID_NOTIFY
};

enum NETWORK_STATE_CHANGE_TYPE
{
	NO_CHANGE = 0,
	DISCONNECTED,
	CONNECTING_TO_AP,
	CONNECTED_TO_AP,
	ACTING_AS_AP,
	UNKNOWN_STATE
};

#endif
